config/routes.rb
Trailblaze::Application.routes.draw do
  resources :users
  get '/trails/mytrails' => 'trails#mytrails', as: 'mytrails'
  resources :trails
  resources :badges

  resources :sessions, only: [:new, :create, :destroy]
  resources :trailmarkers
  root :to => 'static_pages#index'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :badgifications
  has_many :users, :through => :badgification

  def assign_badge

  end
end

app/models/badgification.rb
class Badgification < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
end

app/models/initiation.rb
class Initiation < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail
end

app/models/trail.rb
class Trail < ActiveRecord::Base
	belongs_to :user
	has_many :trailmarkers, :through => :trailification

  	after_create do |trail|
  		puts "Congratulations, you have earned the Pioneer Badge!"
  		unless @current_user.id == Badgification.find(badge.id).user_id
  			redirect_to @trail, success: "Your #{@trail.name} trail has been created!"
  		end 		
  	end
end

app/models/trailification.rb
class Trailification < ActiveRecord::Base
  belongs_to :trail
  belongs_to :trailmarker
end

app/models/trailmarker.rb
class Trailmarker < ActiveRecord::Base
  has_one :trail, :through => :trailification
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trails
  has_many :trailmarkers, :through => :trails
  has_many :badgifications
  has_many :badges, :through => :badgifications
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 80 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.order('name').all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  protected

  def strong_params
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
end

app/controllers/trailmarkers_controller.rb
class TrailmarkersController < ApplicationController
  def index
    @trailmarkers = Trailmarker.order('name').all
  end
  def show
    @trailmarker = Trailmarker.find(params[:id])
  end
  def new
  	@trailmarker = Trailmarker.new
  end
  def create
		@trail = Trailmarker.new(trailmarker_params)
		if @trailmarker.save
			redirect_to trailmarkers_path, notice: "Trailmarker #{@trailmarker.name} was created"
		else
			render 'new'
		end
	end
  def edit
		@trailmarker = Trailmarker.find(params[:id])
  end
  def update
		@trailmarker = Trailmarker.find(params[:id])
		if @trailmarker.update(trailmarker_params)
			redirect_to trails_path, notice: "Trailmarker #{@trailmarker.name} was updated"
		else
			render 'edit'
		end
	end
	def destroy
		@trailmarker = Trailmarker.find(params[:id])
		@trailmarker.destroy
		redirect_to trailmarkers_path, notice: "Trailmarker #{@trailmarker.name} was deleted"
	end
	protected
	def trailmarker_params
		params.require(:trailmarker).permit!
	end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
	layout 'trails_show'


  def index
    @trails = Trail.order('id').all
  end
  def show
    @trail = Trail.find(params[:id])
  	@user = @trail.user
  end
  def new
  	@trail = Trail.new
  end
  def create
		@trail = Trail.new(trail_params)
    @trail.user_id = current_user.id
		if @trail.save
			redirect_to trails_path, notice: "Trail #{@trail.name} was created"
		else
			render 'new'
		end
	end
	def share
	end

  def mytrails
    @trails = Trail.order('id').all
  end

  def edit
		@trail = Trail.find(params[:id])
		@user = @trail.user
    @trailmarkers = Trailmarker.order('name').all
  end
  def update
		@trail = Trail.find(params[:id])
		if @trail.update(trail_params)
			redirect_to trails_path, notice: "Trail #{@trail.name} was updated"
		else
			render 'edit'
		end
	end
	def destroy
		@trail = Trail.find(params[:id])
		@trail.destroy
		redirect_to trails_path, notice: "Trail #{@trail.name} was completed! Congratulations!"
	end
	protected
	def trail_params
		params.require(:trail).permit!
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    @trail = Trail.order('id').all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(strong_params)
    if @user.save
      sign_in @user
      flash[:success] = "User successfully created"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user).params
      flash[:success] = 'Profile updated'
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def strong_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trailmarkers_helper.rb
module TrailmarkersHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/badges/index.html.erb
<h1>My Badges</h1>
<table>
<tr>
  <th>Badge name</th>
  <th>Badge description</th>
  <th>Badge Status</th>
</tr>
  <% @badges.each do |badge| %>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td><%= badge.status %></td>
  <% end %>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
           <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trailblaze</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-image: url(<%= asset_path 'splash.jpg' %>); background-size: 1327px 882px">
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
  </div>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>

app/views/layouts/trails_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trails</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="trail" style="background-image: url(<%= asset_path 'trailblaze_background.jpg' %>); background-repeat: repeat-x; background-height: 882px;">
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
           <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/index.html.erb
<style media="screen" type="text/css">

background: url("https://s3.amazonaws.com/ooomf-com-files/e3kzXuDrTqUhMgaLbUzg_IMGP4385.jpg")

</style>
<html>
<!-- <body background="url(https://s3.amazonaws.com/ooomf-com-files/e3kzXuDrTqUhMgaLbUzg_IMGP4385.jpg)"> -->
<body>
<div class="center hero-unit">
  <h1>Welcome to Trailblaze!</h1>
  <p>Follow your own path or walk beside friends.</p>

  <%= link_to "Start Blazin'", signup_path, class: "btn btn-warning btn-primary" %>
</div>
</body>
</html>

app/views/trailmarkers/edit.html.erb
<h1>Edit Trailmarker</h1>
<p>Did some self-reflection?</p>

<% if @trailmarker.errors.present? %>
	<ul style="color: red">
	<% @trailmarker.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @trailmarker do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>

app/views/trailmarkers/index.html.erb
<h1>My Trailmarkers</h1>
<table>
<tr>
  <th>Trailmarker name</th>
  <th>Trailmarker description</th>
</tr>
	<% @trailmarkers.each do |trailmarker| %>
		<td><%= trailmarker.name %></td>
		<td><%= trailmarker.description %></td>
	<% end %>
</table>

app/views/trailmarkers/new.html.erb
<h1>Trailmarker</h1>
<p>Add a trailmarker.</p>
<%= form_for @trailmarker do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>

app/views/trailmarkers/show.html.erb
<table>
	<h1>Trailmarker</h1>
	<tr>
		<th>ID</th>
		<td><%= @trailmarker.id %></td>
		<th>Name</th>
		<td><%= @trailmarker.name %></td>
		<th>Description</th>
		<td><%= @trailmarker.description %></td>
		<th>Created</th>
		<td><%= time_ago_in_words @trailmarker.created_at %> ago on</td>,
		<td><%= @trailmarker.created_at.strftime('%m/%d/%Y') %></td>
	</tr>
</table>
<%= link_to "back to trailmarkers", trailmarkers_path %>
<%= link_to "back to trails", trails_path %>

app/views/trails/edit.html.erb
<h1>Edit Trail</h1>
<p>Took some time for self-reflection?  Don't be afraid to make changes!</p>

<% if @trail.errors.present? %>
	<ul style="color: red">
	<% @trail.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @trail do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>

<% for trailmarker in @trailmarkers %>
<%= form_for trailmarker do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>
<% end %>

app/views/trails/index.html.erb
<h1>My Trails</h1>
<table class="table table-hover table-bordered" >
<tr>
  <th>Trail</th>
  <th>Description</th>
  <th>Share</th>
  <th>Actions</th>
</tr>
<% @trails.each do |trail| %>
<tr>

		<td><%= link_to trail.name, trail_path(trail) %></td>
		<td><%= trail.description %></td>
		<td><%= mail_to "hello@bitca.mp", "Bitcamp Friends", subject: "example.com" +trail_path(trail).to_s %></td>
		<td>
			<%= link_to 'edit', edit_trail_path(trail), class: 'btn btn-info btn-small' %>
			<%= link_to 'Complete Path', trail_path(trail), class: 'btn btn-success btn-small', method: :delete, data: { confirm: 'Congratulations! Click to confirm.' } %>
		</td>
	<% end %>
</tr>
</table>
<%= link_to 'New Trail', new_trail_path, class: 'btn btn-warning btn-large' %>

app/views/trails/mytrails.html.erb
<table class="table table-hover table-bordered" >
<tr>
  <th>Trail</th>
  <th>Description</th>
  <th>Share</th>
  <th>Actions</th>
</tr>
<% @trails.each do |trail| %>
  <% if trail.user_id == current_user.id %>
<tr>

    <td><%= link_to trail.name, trail_path(trail) %></td>
    <td><%= trail.description %></td>
    <td><%= mail_to "hello@bitca.mp", "Bitcamp Friends", subject: "example.com" +trail_path(trail).to_s %></td>
    <td>
      <%= link_to 'edit', edit_trail_path(trail), class: 'btn btn-info btn-small' %>
      <%= link_to 'Complete Path', trail_path(trail), class: 'btn btn-success btn-small', method: :delete, data: { confirm: 'Congratulations! Click to confirm.' } %>
    </td>
    <% end %>
  <% end %>
</tr>
</table>

app/views/trails/new.html.erb
<h1>Trailhead</h1>
<h3>Start a new trail.</h3>
<div class="row">
  <div class="span6 offset3">
      <%= form_for @trail, :url => trails_path do |f| %>
    	<%= f.label :name %>
    	<%= f.text_field :name %>
    	<%= f.label :description %>
    	<%= f.text_field :description %>
      <br>
      <%= f.check_box :available_to_public %>
      <%= f.label :available_to_public %>
      <br>
    	<%= f.submit "Start Trail", class: "btn btn-large btn-warning" %>
    <% end %>
  </div>
</div>

app/views/trails/show.html.erb
<body class="trail">
<h1>Your trail to success</h1>
<ul>
<li style="display:block; float: left;">
<ul style ="list-style: none; background-color: #FFFFC2;  padding: 50px;">
	<h2>Trailhead</h2>
    <div><li style="color: #306754";>Trail<%= @trail.name %></li></div>
    <div><li style="color: #306754";><%= @trail.description %></li></div>
    <div><li style="color: #306754";>Started<%= time_ago_in_words @trail.created_at %> ago on <%= @trail.created_at.strftime('%m/%d/%Y') %></li></div>
</ul>
</li>
  <div id="content" style="display: block; float: left">
	<table id="trailmarkers" class="table table-hover table-bordered">
  <tr>
    <th>Trailmarker</th>
    <th>Description</th>
    <th>Trailmarker</th>
    <th>Description</th>
    <th>Trailmarker</th>
    <th>Description</th>
  </tr>
  <tr>
      <!-- Trailmarker start -->
      <% @trailmarkers = Trailmarker.order('name').all %>
      <% for trailmarker in @trailmarkers %>
        <div class="trailmarker">
        <td><%= trailmarker.name%></td>
        <td><%= trailmarker.description %></td>
       <!-- Trailmarker end -->
        </div>
      <% end %>
  </tr>
</table>

</body>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
<br>
      <%= f.submit "Create my account", class: "btn btn-large btn-warning" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @trail.any? then %>
	<%= link_to 'View Trails', trails_path, class: 'btn btn-warning btn-large' %>
	<% else %>
	<%= link_to 'New Trail', new_trail_path, class: 'btn btn-warning btn-large' %>
<% end %>
<%= link_to 'View Badges', badges_path, class: 'btn btn-success btn-large' %>